version: '3.8'

services:
  ui:
    image: node:18
    command: npm start
    working_dir: /app
    volumes:
      - ./app/ui:/app
    ports:
      - "8080:8080"
    depends_on:
      - memcached
      - api

  api:
    image: ${project}-${env}:python
    volumes:
      - ./app/api:/app
    environment:
      - MEMCACHED_HOST=memcached:11211
    ports:
      - "5000:5000"
    depends_on:
      - memcached

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
